Repository hmcts/am-org-role-mapping-service, pull requests merged in 2021-08, with the labels that each got.

#311 Am 1510 pact consumer test advance delete
  src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingConsumerTestForAdvanceDelete.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-311

#338 Fixing the CVE's
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-338

#347 Fixing the CVE's CVE-2021-22119
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-347

#349 1579 CVE nimbus lang tang
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-349

#348 disabling static roles pact
  src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingConsumerTestForStaticRoles.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-348
