Repository hmcts/am-org-role-mapping-service, pull requests merged in 2021-09, with the labels that each got.

#408 refactoring ORG and Admin roles junits
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolAdminOrgRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCaseMappingTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-408

#386 Add fortify implementation
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-386

#397 Update build.gradle
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-397

#385 1605 - Removing secrets
  src/main/resources/application.yaml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-385
