Repository hmcts/am-org-role-mapping-service, pull requests merged in 2022-08, with the labels that each got.

#1011 region is not required for hearing roles
  src/functionalTest/resources/features/F-005/S-045.td.json
  src/functionalTest/resources/features/F-005/S-045_DeleteDataForRoleAssignments.td.json
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1011

#1014 combine renovate PR
  build.gradle
  infrastructure/.terraform-version
  infrastructure/terraform.tf
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1014

#1018 Downgrade pact
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1018

#1020 ORM:Code smell fix for RAS and ORM
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/config/DBFlagConfigurtion.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/util/JacksonUtils.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/util/ValidationUtil.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCaseMappingTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1020

#1029 increasing code coverage and mutations
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ParseRequestServiceTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/PersistenceServiceTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshOrchestratorTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RequestMappingServiceTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataServiceTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/launchdarkly/FeatureConditionEvaluatorTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/util/JacksonUtilsTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1029

#1033 fix junit failure in master
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/PersistenceServiceTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1033

#1031 merging the renovate PR
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  infrastructure/.terraform-version
Labels: ns:am, prd:am, no-changes, rel:am-org-role-mapping-service-pr-1031

#1034 merging the renovate PR
  build.gradle
  docker/database/Dockerfile
  infrastructure/terraform.tf
Labels: ns:am, prd:am, no-changes, rel:am-org-role-mapping-service-pr-1034

#1038 Adding privatelaw wa 1.0 flags to DB
  src/main/resources/db/migration/V1.8__privatelaw_wa_base_flag_addition.sql
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1038

#1051 Add backstage configuration file
  catalog-info.yaml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1051
