Repository hmcts/am-org-role-mapping-service, pull requests merged in 2022-10, with the labels that each got.

#1098 CVE issues and build failures
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1098

#1106 Upgrade Jackson Due to CVE
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1106

#1116 white list refresh batch service
  charts/am-org-role-mapping-service/Chart.yaml
  charts/am-org-role-mapping-service/values.yaml
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/config/JobConfiguration.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshOrchestrator.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1116

#1122 fix build failure
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1122

#1127 fix-Nightly Build failure
  build.gradle
  infrastructure/terraform.tf
Labels: ns:am, prd:am, no-changes, rel:am-org-role-mapping-service-pr-1127

#1129 Remove CFT Region and refactor Appointments
  src/functionalTest/resources/features/F-007/S-084.td.json
  src/main/resources/validationrules/civil/civil-judicial-office-holder-mapping.drl
  src/main/resources/validationrules/civil/civil-judicial-org-role-mapping.drl
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilJudicialRoleMappingTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1129
