Repository hmcts/am-org-role-mapping-service, pull requests merged in 2022-03, with the labels that each got.

#704 disable failing judicial scenarios
  src/functionalTest/resources/features/F-003/F-003.feature
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-704

#705 ignore fortify scan failure
  Jenkinsfile_nightly
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-705

#692 test improvements
  build.gradle
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/controller/RefreshControllerTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/controller/WelcomeControllerTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/controller/advice/OrgRoleMappingControllerAdviceTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ParseRequestServiceTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshOrchestratorTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/oidc/IdamRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/util/SecurityUtilsTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-692

#693 AM-1994: FTA fix.
  src/functionalTest/resources/features/F-003/F-003.feature
  src/functionalTest/resources/features/F-003/JRDTribunalJudgeFeepaidUser.td.json
  src/functionalTest/resources/features/F-003/JRDTribunalJudgeSalariedUser.td.json
  src/functionalTest/resources/features/F-003/S-022.td.json
  src/functionalTest/resources/features/F-003/S-023.td.json
  src/functionalTest/resources/features/F-004/F-004.feature
  src/functionalTest/resources/features/F-004/S-031.td.json
  src/functionalTest/resources/features/F-004/S-032.td.json
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-693

#715 Updated the chart version
  charts/am-org-role-mapping-service/Chart.yaml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-715

#706 LD load on startup based on yml flag
  build.gradle
  charts/am-org-role-mapping-service/Chart.yaml
  charts/am-org-role-mapping-service/values.preview.template.yaml
  charts/am-org-role-mapping-service/values.yaml
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/config/LDDummyClient.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/config/LaunchDarklyConfiguration.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/launchdarkly/FeatureConditionEvaluator.java
  src/main/resources/application.yaml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-706

#737 updated some jar bumps
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-737

#738 upgrade drools to remove cve suppression
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-738

#741 Fix CVE-2018-1258
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-741

#742 gradle upgrade to 7.4.1
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingConsumerTestForStaticRoles.java
  src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/BaseTest.java
  src/smokeTest/java/uk/gov/hmcts/reform/orgrolemapping/BaseTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-742

#752 Cve Fix
  build.gradle
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RequestMappingServiceTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-752

#755 Updated poi, poi-ooxml & poi-scratchpad to 5.2.1
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-755

#763 CVE fix
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-763

#766 postgres version update
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-766

#754 hearing channel rules
  src/functionalTest/resources/features/F-003/S-022.td.json
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/enums/FeatureFlagEnum.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/enums/RoleCategory.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/helper/AssignmentRequestBuilder.java
  src/main/resources/META-INF/kmodule.xml
  src/main/resources/db/migration/V1.5__sscs_hearing_flag_config_table.sql
  src/main/resources/validationrules/iac/iac-judicial-office-holder-mapping.drl
  src/main/resources/validationrules/sscs/sscs-caseworker-mapping.drl
  src/main/resources/validationrules/sscs/sscs-judicial-office-holder-mapping.drl
  src/main/resources/validationrules/sscs/sscs-judicial-org-role-mapping.drl
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolHearingOfficeOrgRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/AssignmentRequestBuilderTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/TestDataBuilder.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-754
