Repository hmcts/am-org-role-mapping-service, pull requests merged in 2022-04, with the labels that each got.

#767 removed hearting FTA
  src/functionalTest/java/uk/gov/hmcts/reform/orgrolemapping/befta/OrmDefaultMultiSourceFeatureToggleService.java
  src/functionalTest/resources/features/F-003/F-003.feature
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-767

#756 Drool unit tests for judicial scenarios scss
  build.gradle
  src/main/resources/validationrules/sscs/sscs-judicial-office-holder-mapping.drl
  src/main/resources/validationrules/sscs/sscs-judicial-org-role-mapping.drl
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolJudicialOfficeMappingSscsTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolJudicialRoleMappingSscsTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-756

#778 multiple cve fixes
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-778

#779 Add combine pull request action
  .github/workflows/combine-prs.yml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-779

#780 Remove additional global search role for ogd
  src/main/resources/validationrules/sscs/sscs-admin-mapping.drl
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-780

#783 CVE fix
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-783

#784 CVE fix
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-784

#798 Am helpchart update
  charts/am-org-role-mapping-service/Chart.yaml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-798

#799 flyway file version
  src/functionalTest/resources/features/F-003/S-022.td.json
  src/main/resources/db/migration/V1.5.1__sscs_wa_base_flag_addition.sql
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-799
