Repository hmcts/am-org-role-mapping-service, pull requests merged in 2022-01, with the labels that each got.

#567 Update fortify release ID and enable Fortify scan
  Jenkinsfile_nightly
  config/fortify-client.properties
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-567

#601 Am fortify fix
  src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/WelcomeControllerIntegrationTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-601

#589 AM_1863 sonar conditional coverage
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/controller/RefreshControllerTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/controller/advice/OrgRoleMappingControllerAdviceTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshOrchestratorTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RequestMappingServiceTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/CaseWorkerAccessProfileBuilderTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/oidc/IdamRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/util/SecurityUtilsTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/util/ValidationUtilTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-589

#590 Judicial refresh fta
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  src/functionalTest/java/uk/gov/hmcts/reform/orgrolemapping/befta/OrgRoleMappingAmTestAutomationAdapter.java
  src/functionalTest/resources/features/F-004/F-004-Base-Root.td.json
  src/functionalTest/resources/features/F-004/F-004.feature
  src/functionalTest/resources/features/F-004/F-004_Test_Data_Base.td.json
  src/functionalTest/resources/features/F-004/S-031.td.json
  src/functionalTest/resources/features/F-004/S-031_CreateDataForBookings.td.json
  src/functionalTest/resources/features/F-004/S-031_DeleteDataForBookings.td.json
  src/functionalTest/resources/features/F-004/S-031_DeleteDataForRoleAssignments.td.json
  src/functionalTest/resources/features/F-004/S-031_PostRefreshRequestToORM.td.json
  src/functionalTest/resources/features/F-004/S-032.td.json
  src/functionalTest/resources/features/F-004/S-032_CreateDataForBookings.td.json
  src/functionalTest/resources/features/F-004/S-032_CreateDataForNewBookings.td.json
  src/functionalTest/resources/features/F-004/S-032_DeleteDataForBookings.td.json
  src/functionalTest/resources/features/F-004/S-032_DeleteDataForRoleAssignments.td.json
  src/functionalTest/resources/features/F-004/S-032_PostRefreshRequestToORM.td.json
  src/functionalTest/resources/features/F-004/S-033.td.json
  src/functionalTest/resources/features/F-004/S-033_DeleteDataForBookings.td.json
  src/functionalTest/resources/features/F-004/S-033_DeleteDataForRoleAssignments.td.json
  src/functionalTest/resources/features/F-004/S-033_PostRefreshRequestToORM.td.json
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-590

#610 Create Judicial Booking Consumer Pact Test
  Jenkinsfile_CNP
  build.gradle
  src/contractTest/java/uk/gov/hmcts/reform/judicialbooking/JudicialBookingCreateConsumerTest.java
  src/contractTest/java/uk/gov/hmcts/reform/judicialbooking/JudicialBookingQueryConsumerTest.java
  src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/provider/OrgRoleMappingProviderTestForRefresh.java
  src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/provider/ProviderTestConfiguration.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-610

#609 orm fta updated inline with correct LD flag
  src/functionalTest/resources/features/F-004/F-004.feature
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-609

#631 Fix ORM Pact Verification Publish to Remote Broker
  Jenkinsfile_CNP
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-631

#637 Test PR for FTA with IAC 2_0 flag
  README.md
  src/functionalTest/resources/features/F-001/F-001.feature
  src/functionalTest/resources/features/F-001/S-002.td.json
  src/functionalTest/resources/features/F-001/S-006.td.json
  src/functionalTest/resources/features/F-001/S-010.td.json
  src/functionalTest/resources/features/F-003/F-003.feature
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-637

#639 updated scenario 7 to identify duplicate
  src/functionalTest/resources/features/F-001/F-001.feature
  src/functionalTest/resources/features/F-001/S-007.td.json
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-639

#638 Fix Pact Publish
  Jenkinsfile_CNP
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-638

#641 removing deprecated jcenter
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-641
