Repository hmcts/am-org-role-mapping-service, pull requests merged in 2023-03, with the labels that each got.

#1359 ORM:CIVIL_HMC - Add hearing roles for Civil service
  src/functionalTest/resources/features/F-007/S-061.td.json
  src/functionalTest/resources/features/F-007/S-062.td.json
  src/functionalTest/resources/features/F-007/S-063.td.json
  src/functionalTest/resources/features/F-007/S-081.td.json
  src/functionalTest/resources/features/F-007/S-082.td.json
  src/functionalTest/resources/features/F-007/S-084.td.json
  src/main/resources/validationrules/core/hearing-role-admin-global.drl
  src/main/resources/validationrules/core/hearing-role-caseworker-global.drl
  src/main/resources/validationrules/core/hearing-role-ctsc-global.drl
  src/main/resources/validationrules/core/hearing-role-judicial-global.drl
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilHearingJudicialRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolHearingOfficeOrgRoleMappingTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1359

#1387 ORM and Refresh Batch-Application Nightly Build failed
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1387

#1396 AM-2686:Pact fix for reading from Project instead of System
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1396

#1418 AM-2728 CVR-2022-1471 snakeyaml suppression added, unrequired suppres…
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1418

#1419 helm upgrade
  charts/am-org-role-mapping-service/Chart.yaml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1419

#1395 ORM:Change in mappings for fee paid judges for services
  build.gradle
  src/functionalTest/resources/features/F-003/S-021.td.json
  src/functionalTest/resources/features/F-003/S-022.td.json
  src/functionalTest/resources/features/F-003/S-024.td.json
  src/functionalTest/resources/features/F-007/S-084.td.json
  src/functionalTest/resources/features/F-008/S-073.td.json
  src/integrationTest/resources/RASTribunalJudgeFeePaid.json
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1395

#1422 AM-2733 CVE-2023-28708 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1422

#1424 AM-2737 CVE-2023-20861 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1424
