Repository hmcts/am-org-role-mapping-service, pull requests merged in 2023-02, with the labels that each got.

#1311 dependency check upgrade
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1311

#1312 Fix Code smell issues
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCtscOrgRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolPublicLawStaffOrgRolesTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1312

#1332 SSCS_HEARING - Add new business roles for SSCS
  src/main/resources/validationrules/core/hearing-role-admin-global.drl
  src/main/resources/validationrules/core/hearing-role-caseworker-global.drl
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolHearingOfficeOrgRoleMappingTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1332

#1364 swagger changes
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1364

#1368 ORM:Application Nightly build failed due to CVE-2022-45688
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1368

#1370 Fix warnings
  src/main/resources/application.yaml
  src/main/resources/config.properties
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1370

#1376 fix orm build
  Jenkinsfile_CNP
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1376
