Repository hmcts/am-org-role-mapping-service, pull requests merged in 2023-09, with the labels that each got.

#1562 AM-2923 CVE-2023-41080 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1562

#1568 AM-2924 Remove keep-helm
  Jenkinsfile_CNP
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1568, enable_keep_helm

#1570 AM-2923 CVE-2023-41080 tomcat upgraded to 9.0.80
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1570

#1530 AM-2872 eLinks Consume V2 Data - first commit
  orm-wiremocks-docker/.env
  orm-wiremocks-docker/README.md
  orm-wiremocks-docker/compose/orm-wiremocks.yml
  orm-wiremocks-docker/mocks/wiremock/__files/jrd/refreshUserProfile.json.hbs
  orm-wiremocks-docker/mocks/wiremock/mappings/health.json
  orm-wiremocks-docker/mocks/wiremock/mappings/jrd/refreshUserProfile.json
  src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/provider/ProviderTestConfiguration.java
  src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/RefreshControllerIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/AppointmentV2.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/AuthorisationV2.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/JudicialProfileV2.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/RoleV2.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ParseRequestService.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataService.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/feignclients/configuration/RdFeignClientInterceptor.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/helper/AssignmentRequestBuilder.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/helper/UserAccessProfileBuilder.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/util/JacksonUtils.java
  src/main/resources/application.yaml
  src/main/resources/judicialProfileSampleV2.json
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/JRDServiceTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/JudicialRefreshOrchestratorTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ParseRequestServiceTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataServiceTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/AssignmentRequestBuilderTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/CaseWorkerAccessProfileBuilderTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/TestDataBuilder.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/util/JacksonUtilsTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1530

#1574 Am 2871 fix model element name
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/RoleV2.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/helper/AssignmentRequestBuilder.java
  src/main/resources/judicialProfileSampleV2.json
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilJudicialRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/AssignmentRequestBuilderTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/TestDataBuilder.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1574

#1569 AM-2921 Update Renovate Config
  renovate.json
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1569

#1573 JRD_eLinks_2_0 Release/feature branch
  charts/am-org-role-mapping-service/Chart.yaml
  charts/am-org-role-mapping-service/values.preview.template.yaml
  charts/am-org-role-mapping-service/values.yaml
  orm-wiremocks-docker/.env
  orm-wiremocks-docker/README.md
  orm-wiremocks-docker/compose/orm-wiremocks.yml
  orm-wiremocks-docker/mocks/wiremock/__files/jrd/refreshUserProfile.json.hbs
  orm-wiremocks-docker/mocks/wiremock/mappings/health.json
  orm-wiremocks-docker/mocks/wiremock/mappings/jrd/refreshUserProfile.json
  src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/provider/ProviderTestConfiguration.java
  src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/RefreshControllerIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/AppointmentV2.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/AuthorisationV2.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/JudicialProfileV2.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/RoleV2.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/constants/JudicialAccessProfile.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ParseRequestService.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataService.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/feignclients/configuration/RdFeignClientInterceptor.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/helper/AssignmentRequestBuilder.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/helper/UserAccessProfileBuilder.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/util/JacksonUtils.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/util/UtilityFunctions.java
  src/main/resources/application.yaml
  src/main/resources/judicialProfileSampleV2.json
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilJudicialRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/JRDServiceTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/JudicialRefreshOrchestratorTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ParseRequestServiceTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataServiceTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/AssignmentRequestBuilderTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/CaseWorkerAccessProfileBuilderTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/TestDataBuilder.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/util/JacksonUtilsTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/util/UtilityFunctionsTest.java
Labels: ns:am, prd:am, enable_keep_helm, rel:am-org-role-mapping-service-pr-1573

#1576 Cot 519 fpl add extra roles
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/enums/FeatureFlagEnum.java
  src/main/resources/db/migration/V20230912_519__COT-519_PUBLICLAW_WA_1_1_base_flag_addition.sql
  src/main/resources/validationrules/core/hearing-role-judicial-global.drl
  src/main/resources/validationrules/publiclaw/publiclaw-judicial-office-holder-mapping.drl
  src/main/resources/validationrules/publiclaw/publiclaw-judicial-org-role-mapping.drl
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolPublicLawJudicialRoleMappingTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1576

#1577 AM-2885 CVE-2023-3635 okio 3.5.0 dependencySet added
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, enable_keep_helm, rel:am-org-role-mapping-service-pr-1577

#1580 AM-2894 patch to PR 1540
  charts/am-org-role-mapping-service/values.aat.template.yaml
  charts/am-org-role-mapping-service/values.preview.template.yaml
  charts/am-org-role-mapping-service/values.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/config/SwaggerPublisher.java
  src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/WelcomeControllerIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/controller/WelcomeController.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/controller/testingsupport/OrgMappingController.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/CRDMessagingConfiguration.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/CRDTopicPublisher.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/JRDMessagingConfiguration.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/JRDTopicPublisher.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/TopicController.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/controller/WelcomeControllerTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/controller/testingsupport/OrgMappingControllerTest.java
Labels: ns:am, prd:am, enable_keep_helm, rel:am-org-role-mapping-service-pr-1580

#1584 AM-2938 Enable `publiclaw_wa_1_1` ORM flag in PROD
  src/main/resources/db/migration/V20230921_2938__AM-2938_Enable_publiclaw_wa_1_1_Prod.sql
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1584

#1585 AM-2941 Move away from using `Docker.io` for images referenced by AM …
  charts/am-org-role-mapping-service/Chart.yaml
Labels: ns:am, prd:am, enable_keep_helm, rel:am-org-role-mapping-service-pr-1585

#1578 AM-2918 eLinks V2 Pact Test Improvement - extra coverage of data …
  src/contractTest/java/uk/gov/hmcts/reform/refdata/RefDataJudicialProfileConsumerTestV2.java
  src/main/resources/judicialProfileSampleV2.json
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1578

#1566 AM-2918 JRD eLinks V2 PACT test
  src/contractTest/java/uk/gov/hmcts/reform/refdata/RefDataJudicialProfileConsumerTestV2.java
  src/main/resources/judicialProfileSampleV2.json
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1566
