Repository hmcts/am-org-role-mapping-service, pull requests merged in 2023-07, with the labels that each got.

#1488 AM-2854 CVE-2023-34462 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1488

#1434 EMPLOYMENT_WA_1_0 Release/feature branch
  build.gradle
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/enums/FeatureFlagEnum.java
  src/main/resources/META-INF/kmodule.xml
  src/main/resources/db/migration/V1.10__employment_wa_base_flag_addition.sql
  src/main/resources/validationrules/core/hearing-role-admin-global.drl
  src/main/resources/validationrules/core/hearing-role-caseworker-global.drl
  src/main/resources/validationrules/core/hearing-role-ctsc-global.drl
  src/main/resources/validationrules/core/hearing-role-judicial-global.drl
  src/main/resources/validationrules/core/utility-functions.drl
  src/main/resources/validationrules/employment/employment-admin-mapping.drl
  src/main/resources/validationrules/employment/employment-caseworker-mapping.drl
  src/main/resources/validationrules/employment/employment-ctsc-mapping.drl
  src/main/resources/validationrules/employment/employment-judicial-office-holder-mapping.drl
  src/main/resources/validationrules/employment/employment-judicial-org-role-mapping.drl
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolEmploymentHearingJudicialRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolEmploymentJudicialRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolEmploymentStaffOrgRolesTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolHearingOfficeOrgRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/TestDataBuilder.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1434

#1489 AM-2844 ET Flyway config OutOfOrder trying to fix AAT deployment
  src/main/resources/application.yaml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1489

#1484 Cot 368 update fpl staff judicial work types
  src/main/resources/validationrules/publiclaw/publiclaw-admin-mapping.drl
  src/main/resources/validationrules/publiclaw/publiclaw-caseworker-mapping.drl
  src/main/resources/validationrules/publiclaw/publiclaw-ctsc-mapping.drl
  src/main/resources/validationrules/publiclaw/publiclaw-judicial-org-role-mapping.drl
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolPublicLawJudicialRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolPublicLawStaffOrgRolesTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1484

#1344 2638 upgrade spring boot
  README.md
  build.gradle
  charts/am-org-role-mapping-service/values.preview.template.yaml
  src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/provider/OrgRoleMappingProviderTestForRefresh.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/config/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/controller/FeatureFlagController.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/controller/RefreshController.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/controller/TestController.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/controller/WelcomeController.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/RoleAssignmentRequestResource.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/oidc/JwtGrantedAuthoritiesConverter.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/TopicController.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/util/Swagger2SpringBoot.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/controller/WelcomeControllerTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/oidc/JwtGrantedAuthoritiesConverterTest.java
Labels: ns:am, prd:am, no-changes, rel:am-org-role-mapping-service-pr-1344

#1446 Am 2798 publish swagger docs
  .github/workflows/swagger.yml
  src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/provider/OrgRoleMappingProviderTestForRefresh.java
  src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/config/SwaggerPublisher.java
  src/main/resources/application.yaml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1446

#1485 AM-2846: For preview pipelines enable cleanup of helm releases
  Jenkinsfile_CNP
Labels: ns:am, prd:am, keep-helm, rel:am-org-role-mapping-service-pr-1485

#1490 AM-2823 CVE-2023-20883 plugin org.springframework.boot upgraded 2.6.1…
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1490

#1487 AM-2852 CVE-2023-34981 tomcat upgrade 9.0.76
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1487

#1492 AM-2854 CVE-2023-34462 Netty upgraded 4.1.94.Final
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1492

#1495 AM-2728 CVE-2022-1471 snakeyaml 2.0, springBoot 2.7.12, launchDarklyS…
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1495

#1497 AM-2860 Remove Github Autoupdate
  .github/workflows/autoupdate.yml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1497

#1483 AM-2842: Reduce amount of logging in App Insights for /health
  lib/applicationinsights.json
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1483

#1493 SSCS_WA_1_0:WA address review comments
  src/main/resources/validationrules/sscs/sscs-judicial-office-holder-mapping.drl
  src/main/resources/validationrules/sscs/sscs-judicial-org-role-mapping.drl
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolAdminOrgRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolHearingOfficeOrgRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolSscsJudicialOfficeMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolSscsJudicialRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolSscsStaffOrgRolesTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1493

#1500 AM-2738 Nightly build slack messaging removed
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1500

#1499 AM-2863 CVE-2022-45688 org.json:json upgraded to 20230227 which shoul…
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1499

#1503 AM-2851 CVE-2023-2976 guava 32.0.1-jre, launchDarklySdk 5.10.9, suppr…
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1503

#1501 SSCS_WA_1_0:WA FTs
  Jenkinsfile_CNP
  charts/am-org-role-mapping-service/values.preview.template.yaml
  src/functionalTest/resources/features/F-004/S-031.td.json
  src/functionalTest/resources/features/F-004/S-032.td.json
  src/functionalTest/resources/features/F-005/S-042.td.json
  src/functionalTest/resources/features/F-005/S-043.td.json
  src/functionalTest/resources/features/F-005/S-044.td.json
  src/functionalTest/resources/features/F-006/S-051.td.json
  src/functionalTest/resources/features/F-006/S-052.td.json
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1501

#1504 AM-2762 AM-2763 SSCS_WA Additional WA Config - Release Endpoint Tweak
  Jenkinsfile_CNP
  charts/am-org-role-mapping-service/values.preview.template.yaml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1504

#1478 COT-358 - flyway script to enable FPL in prod
  src/main/resources/db/migration/V20230620_358__COT-358_WA_enable_PUBLICLAW_flag_in_PROD.sql
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1478

#1512 AM-2869 CVE-2023-34036 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1512

#1513 AM-2869 CVE-2023-34036 spring-hateoas 1.5.5
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1513

#1514 AM-2866 - ST_CIC_WA: WA address review comments
  src/main/resources/validationrules/stcic/stcic-judicial-office-holder-mapping.drl
  src/main/resources/validationrules/stcic/stcic-judicial-org-role-mapping.drl
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolStcicJudicialOfficeMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolStcicJudicialRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolStcicStaffOrgRoleTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1514

#1515 AM-2876 Checkstyle Code Formatting for uk.gov.hmcts.java 0.12.43 - in…
  build.gradle
  src/contractTest/java/uk/gov/hmcts/reform/judicialbooking/JudicialBookingConsumerApplication.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/OrgRoleMappingApplication.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/controller/RefreshController.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/controller/WelcomeController.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilJudicialRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCtscOrgRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolEmploymentJudicialRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolEmploymentStaffOrgRolesTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolHearingOfficeOrgRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolPrivateLawStaffOrgRolesTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolPublicLawStaffOrgRolesTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolSscsJudicialOfficeMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolSscsJudicialRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolSscsStaffOrgRolesTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/launchdarkly/FeatureConditionEvaluatorTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1515

#1526 AM-2878 FTA report link missing in Master pipelines - publishHTML sec…
  Jenkinsfile_CNP
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1526

#1528 AM-2885 CVE-2023-3635 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1528

#1532 AM-2888 CVE-2023-34034 AM-2889 CVE-2023-3782 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1532
