Repository hmcts/am-org-role-mapping-service, pull requests merged in 2023-06, with the labels that each got.

#1447 AM-2638 Adjust swagger config in PR-1344
  README.md
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/controller/FeatureFlagController.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/controller/RefreshController.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/controller/WelcomeController.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/util/Swagger2SpringBoot.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/controller/WelcomeControllerTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1447

#1459 COT-306 update fpl staff role mappings
  src/main/resources/validationrules/publiclaw/publiclaw-admin-mapping.drl
  src/main/resources/validationrules/publiclaw/publiclaw-caseworker-mapping.drl
  src/main/resources/validationrules/publiclaw/publiclaw-ctsc-mapping.drl
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolPublicLawStaffOrgRolesTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1459

#1463 AM-2638 Adjust flag controller config in PR-1344
  src/main/resources/application.yaml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1463

#1456 Am 2714 st cic wa mapping rules judicial
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/enums/FeatureFlagEnum.java
  src/main/resources/META-INF/kmodule.xml
  src/main/resources/db/migration/V20230512_2714__AM-2714_ST_CIC_WA_1_0_base_flag_addition.sql
  src/main/resources/validationrules/specialtribunals/specialtribunals-judicial-office-holder-mapping.drl
  src/main/resources/validationrules/specialtribunals/specialtribunals-judicial-org-role-mapping.drl
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolSpecialTribunalsJudicialRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/TestDataBuilder.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1456

#1458 Am 2716 st cic wa mapping rules staff
  src/main/resources/META-INF/kmodule.xml
  src/main/resources/validationrules/stcic/stcic-admin-mapping.drl
  src/main/resources/validationrules/stcic/stcic-caseworker-mapping.drl
  src/main/resources/validationrules/stcic/stcic-ctsc-mapping.drl
  src/main/resources/validationrules/stcic/stcic-judicial-office-holder-mapping.drl
  src/main/resources/validationrules/stcic/stcic-judicial-org-role-mapping.drl
  src/main/resources/validationrules/stcic/stcic-other-mapping.drl
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolStcicJudicialRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolStcicStaffOrgRoleTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1458

#1467 AM-2823-CVE-2023-20883 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1467

#1475 AM-2826: S-073 updated query.
  src/functionalTest/resources/features/F-008/S-073.td.json
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1475

#1470 AM-2831 Code Review Changes For #1434
  src/main/resources/validationrules/employment/employment-admin-mapping.drl
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolEmploymentJudicialRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolEmploymentStaffOrgRolesTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1470

#1477 AM-2821: Remove redundant tests
  src/functionalTest/resources/features/F-007/F-007.feature
  src/functionalTest/resources/features/F-007/S-061.td.json
  src/functionalTest/resources/features/F-007/S-061.v1_1.td.json
  src/functionalTest/resources/features/F-007/S-082.td.json
  src/functionalTest/resources/features/F-007/S-082.v1_1.td.json
  src/functionalTest/resources/features/F-008/F-008.feature
  src/functionalTest/resources/features/F-008/S-071.td.json
  src/functionalTest/resources/features/F-008/S-071.v1_0.td.json
  src/functionalTest/resources/features/F-008/S-071.v1_1.td.json
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1477

#1481 AM-2839 CVE-2023-35116 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1481

#1486 AM-2851 CVE-2023-2976 and AM-2852 CVE-2023-34981 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1486

#1480 AM-2776 CVE-2023-20863 spring framework upgrade 5.3.27
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1480

#1479 AM-2835: Configure arrays in FTAs so where possible they are unordered
  build.gradle
  src/functionalTest/resources/features/F-001/S-002.td.json
  src/functionalTest/resources/features/F-001/S-007.td.json
  src/functionalTest/resources/features/F-004/S-032.td.json
  src/functionalTest/resources/features/F-005/S-043.td.json
  src/functionalTest/resources/features/F-005/S-044.td.json
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1479
