Repository hmcts/am-org-role-mapping-service, pull requests merged in 2023-11, with the labels that each got.

#1630 AM-2983 Connect to v15 JBS ITHC - Remove 'ithc' from git branchesToSync
  Jenkinsfile_CNP
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1630

#1622 Am 2996 provision terraform postgres v15 perftest
  infrastructure/main.tf
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:am, prd:am, add-or-update, rel:am-org-role-mapping-service-pr-1622

#1632 AM-2996 Provision Terraform Postgres v15 - subnet_suffix = "expanded"
  infrastructure/main.tf
Labels: ns:am, prd:am, add-or-update, rel:am-org-role-mapping-service-pr-1632

#1633 AM-3048 Retire Bootstrap yaml
  charts/am-org-role-mapping-service/Chart.yaml
  charts/am-org-role-mapping-service/values.preview.template.yaml
  charts/am-org-role-mapping-service/values.yaml
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1633

#1637 AM-2976 Provision Terraform v15 server ITHC Expanded Subnet
  infrastructure/main.tf
Labels: ns:am, prd:am, add-or-update, rel:am-org-role-mapping-service-pr-1637

#1625 AM-3021 Provision terraform v15 server Prod AAT
  infrastructure/main.tf
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:am, prd:am, add-or-update, rel:am-org-role-mapping-service-pr-1625

#1644 AM-2839 CVE-2023-35116 jackson upgraded to 2.15.3, Remove Suppression
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1644

#1654 AM-3065 CVE-2023-36052 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1654

#1650 AM-3061 v15 Reader User Trigger
  infrastructure/main.tf
Labels: ns:am, prd:am, destroy, rel:am-org-role-mapping-service-pr-1650

#1655 AM-2840 CVE-2022-45688 Remove Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1655

#1656 AM-3068 Pitest failures in Nightly - pitest-junit5-plugin upgraded to…
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1656

#1649 AM-2917 FTA changes for JRD V2 switchover
  charts/am-org-role-mapping-service/values.preview.template.yaml
  orm-wiremocks-docker/mocks/wiremock/__files/jrd/refreshUserProfile.json.hbs
  src/functionalTest/resources/features/F-003/S-022.td.json
  src/functionalTest/resources/features/F-005/S-045.td.json
  src/functionalTest/resources/features/F-005/S-045_DeleteDataForRoleAssignments.td.json
  src/functionalTest/resources/features/F-007/S-081.td.json
  src/functionalTest/resources/features/F-007/S-084.td.json
  src/functionalTest/resources/features/F-008/S-073.td.json
  src/functionalTest/resources/features/F-008/S-073_JRDCircuitJudgeFeePaidUser.td.json
  src/functionalTest/resources/features/F-009/S-094.td.json
  src/functionalTest/resources/features/F-009/S-095.td.json
  src/functionalTest/resources/features/F-009/S-095_JRDJudgeSalariedUser.td.json
  src/main/resources/application.yaml
Labels: ns:am, prd:am, no-changes, enable_keep_helm, rel:am-org-role-mapping-service-pr-1649

#1661 AM-2917 FTA updates to reflect data change after JRD V2 switchover - …
  charts/am-org-role-mapping-service/values.aat.template.yaml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1661

#1667 AM-2917 Tidy up
  orm-wiremocks-docker/mocks/wiremock/__files/jrd/refreshUserProfile.json.hbs
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1667

#1660 COT-597 Add Tribunal Judges to Civil WA config
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/enums/FeatureFlagEnum.java
  src/main/resources/db/migration/V20231123_597__COT-597_CIVIL_WA_1_3_base_flag_addition.sql
  src/main/resources/validationrules/civil/civil-judicial-office-holder-mapping.drl
  src/main/resources/validationrules/civil/civil-judicial-org-role-mapping.drl
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilHearingJudicialRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilJudicialRoleMappingTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1660

#1645 FTA for Legal Ops ORG roles.
  src/functionalTest/resources/features/F-010/F-010-Base-Root.td.json
  src/functionalTest/resources/features/F-010/F-010.feature
  src/functionalTest/resources/features/F-010/F-010_Test_Data_Base.td.json
  src/functionalTest/resources/features/F-010/S-101.td.json
  src/functionalTest/resources/features/F-010/S-101_DeleteDataForRoleAssignments.td.json
  src/functionalTest/resources/features/F-010/S-101_PushMessageToCRDService.td.json
  src/functionalTest/resources/features/F-010/S-101_SingleUserMultipleCaseworkerRolesIds.td.json
  src/functionalTest/resources/features/F-010/S-102.td.json
  src/functionalTest/resources/features/F-010/S-102_DeleteDataForRoleAssignments.td.json
  src/functionalTest/resources/features/F-010/S-102_PushMessageToCRDService.td.json
  src/functionalTest/resources/features/F-010/S-102_SingleUserMultipleHearingRolesIds.td.json
  src/functionalTest/resources/features/F-010/S-103.td.json
  src/functionalTest/resources/features/F-010/S-103_DeleteDataForRoleAssignments.td.json
  src/functionalTest/resources/features/F-010/S-103_PushMessageToCRDService.td.json
  src/functionalTest/resources/features/F-010/S-103_SingleUserMultipleHearingRolesIds.td.json
  src/functionalTest/resources/features/F-010/S-104.td.json
  src/functionalTest/resources/features/F-010/S-104_DeleteDataForRoleAssignments.td.json
  src/functionalTest/resources/features/F-010/S-104_PushMessageToCRDService.td.json
  src/functionalTest/resources/features/F-010/S-104_SingleUserMultipleHearingRolesIds.td.json
  src/functionalTest/resources/features/F-010/S-105.td.json
  src/functionalTest/resources/features/F-010/S-105_DeleteDataForRoleAssignments.td.json
  src/functionalTest/resources/features/F-010/S-105_PushMessageToCRDService.td.json
  src/functionalTest/resources/features/F-010/S-105_SingleUserMultipleHearingRolesIds.td.json
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1645
