Repository hmcts/am-org-role-mapping-service, pull requests merged in 2023-05, with the labels that each got.

#1438 AM-2786 CVE-2023-20873 AM-2787 CVE-2023-20862 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1438

#1442 AM-2786 CVE-2023-20873 spring-cloud-starter-bootstrap upgraded 3.0.6 …
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1442

#1452 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1452

#1453 AM-2808 ORM PREVIEW migrate from OSBA to ASO
  charts/am-org-role-mapping-service/Chart.yaml
  charts/am-org-role-mapping-service/values.preview.template.yaml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1453

#1455 nightly cron timing corrected
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1455

#1461 AM-2816 CVE-2023-28709 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1461
