Repository hmcts/am-org-role-mapping-service, pull requests merged in 2024-11, with the labels that each got.

#2128 DTSAM-575 `CIVIL_WA_2_0` configure `Deputy District Judge` appointment
  src/functionalTest/resources/features/F-007/F-007.feature
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/enums/FeatureFlagEnum.java
  src/main/resources/db/migration/V20241014_575__DTSAM-575_CIVIL_WA_2_0_base_flag_addition.sql
  src/main/resources/validationrules/civil/civil-judicial-office-holder-mapping.drl
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilHearingJudicialRoleMappingTest.java
Labels: ns:am, prd:am, enable_keep_helm, aat/no-changes, prod/no-changes, rel:am-org-role-mapping-service-pr-2128

#2151 Revert "DTSAM-578 CVE-2024-9329 glassfish Suppression"
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-2151

#2152 DTSAM-88 CVE-2023-36052 azure remove suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-2152

#2153 DTSAM-602 CVE-2024-38820 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-2153

#2155 COT-917: Add removed judge and bookable for identified fee-paid judge
  src/functionalTest/resources/features/F-012/S-128.td.json
  src/main/resources/validationrules/stcic/stcic-judicial-org-role-mapping.drl
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolStcicJudicialRoleMappingTest.java
Labels: ns:am, prd:am, enable_keep_helm, rel:am-org-role-mapping-service-pr-2155

#2169 DTSAM-523-Enable st_cic_wa_1_0 flag in prod
  src/main/resources/db/migration/V20241128_523__DTSAM-523_Enable_st_cic_wa_1_0_Prod.sql
Labels: ns:am, prd:am, DO NOT MERGE, rel:am-org-role-mapping-service-pr-2169
