Repository hmcts/am-org-role-mapping-service, pull requests merged in 2024-05, with the labels that each got.

#1876 AM-3036 Schema Owner Trigger 5
  infrastructure/main.tf
Labels: ns:am, prd:am, aat/destroy, rel:am-org-role-mapping-service-pr-1876, prod/no-changes

#1877 AM-3061 Reader User Trigger 5 Prod
  infrastructure/main.tf
Labels: ns:am, prd:am, aat/destroy, rel:am-org-role-mapping-service-pr-1877, prod/destroy

#1705 AM-3040 Connect to v15 Prod
  charts/am-org-role-mapping-service/Chart.yaml
  charts/am-org-role-mapping-service/values.yaml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1705

#1575 AM-2911: Judicial Refresh (via ASB or Job) to include Judicial Bookings
  charts/am-org-role-mapping-service/values.preview.template.yaml
  src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/provider/OrgRoleMappingProviderTestForRefresh.java
  src/contractTest/java/uk/gov/hmcts/reform/orgrolemapping/provider/ProviderTestConfiguration.java
  src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/RefreshControllerIntegrationV2Test.java
  src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/RefreshControllerJudicialRefreshIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/RefreshControllerRefreshJobIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/WelcomeControllerIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/utils/MockUtils.java
  src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/helper/IntTestDataBuilder.java
  src/integrationTest/resources/sql/insert_refresh_jobs.sql
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/Appointment.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/JudicialAccessProfile.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/JudicialProfile.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/BulkAssignmentOrchestrator.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/JudicialBookingService.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/JudicialRefreshOrchestrator.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ParseRequestService.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshOrchestrator.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RequestMappingService.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataService.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/feignclients/configuration/JRDFeignClientFallback.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/feignclients/configuration/RdFeignClientInterceptor.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/helper/AssignmentRequestBuilder.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/helper/UserAccessProfileBuilder.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/util/JacksonUtils.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/util/UtilityFunctions.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/controller/utils/WiremockFixtures.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/BulkAssignmentOrchestratorTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilJudicialRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolEmploymentJudicialRoleMappingTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/JRDServiceTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/JudicialBookingServiceTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/JudicialRefreshOrchestratorTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/ParseRequestServiceTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshOrchestratorTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RequestMappingServiceTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RetrieveDataServiceTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/AssignmentRequestBuilderTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/CaseWorkerAccessProfileBuilderTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/TestDataBuilder.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/util/JacksonUtilsTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/util/UtilityFunctionsTest.java
Labels: ns:am, prd:am, destroy, enable_keep_helm, rel:am-org-role-mapping-service-pr-1575, aat/destroy, prod/destroy

#1901 DTSAM-286 Adjust error handling in new ASB message process
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/config/servicebus/CRDMessagingConfiguration.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/config/servicebus/JRDMessagingConfiguration.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/PublishCaseWorkerData.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/TopicConsumer.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/servicebus/TopicConsumerTest.java
Labels: ns:am, prd:am, enable_keep_helm, rel:am-org-role-mapping-service-pr-1901

#1910 DTSAM-293 Intermittent Int Test @Disabled shouldProcessRefreshRoleAss…
  src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/controller/RefreshControllerRefreshJobIntegrationTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1910

#1908 DTSAM-303 Resize PG Default - pgsql_sku added and defaulted to GP_Sta…
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:am, prd:am, aat/no-changes, prod/no-changes, rel:am-org-role-mapping-service-pr-1908

#1917 DTSAM-246 Retire old rules after PRIVATELAW_WA_1_4 Go Live - removed …
  src/main/resources/validationrules/privatelaw/privatelaw-other-mapping.drl
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1917

#1911 AM-3046 Decommission Postgres V11 - Point vars POSTGRES-PASS, POSTGRE…
  infrastructure/main.tf
Labels: ns:am, prd:am, aat/add-or-update, ithc/add-or-update, rel:am-org-role-mapping-service-pr-1911

#1912 AM-3046 Decommission V11 DB - Unsync ITHC branch from Master branch
  Jenkinsfile_CNP
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1912

#1924 AM-3046 Decommission Postgres V11 Master - Point vars POSTGRES-PASS, …
  infrastructure/main.tf
Labels: ns:am, prd:am, aat/add-or-update, prod/add-or-update, rel:am-org-role-mapping-service-pr-1924

#1925 AM-3046 Decommission V11 DB - Enable DB Migration in Jenkins build fo…
  Jenkinsfile_CNP
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1925

#1926 DTSAM-3046 Decommission V11 DB Master - V11 TF module removed, azurer…
  infrastructure/main.tf
  infrastructure/terraform.tf
Labels: ns:am, prd:am, aat/destroy, prod/destroy, rel:am-org-role-mapping-service-pr-1926

#1927 Revert "AM-3046 Decommission V11 DB - Unsync ITHC branch from Master branch"
  Jenkinsfile_CNP
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1927

#1933 DTSAM-324: Fix ORM FTAs that have expired judicial appointments
  src/functionalTest/resources/features/F-006/S-059.td.json
  src/functionalTest/resources/features/F-006/S-059_JRDTribunalJudgeFeePaidUser.td.json
  src/functionalTest/resources/features/F-010/S-107_JRDEmploymentJudgeFeePaidUser.td.json
Labels: ns:am, prd:am, enable_keep_helm, rel:am-org-role-mapping-service-pr-1933

#1934 DTSAM-325 Upgrade azurerm to 3.105.0 after V11 Decommission
  infrastructure/terraform.tf
Labels: ns:am, prd:am, aat/no-changes, prod/no-changes, rel:am-org-role-mapping-service-pr-1934

#1928 DTSAM-323 Update AAT Chart Files After V11 Decommission - Hardcoded v…
  charts/am-org-role-mapping-service/values.aat.template.yaml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1928

#1929 DTSAM-320 Decommission custom Postgres-V15 key vault values now that …
  charts/am-org-role-mapping-service/Chart.yaml
  charts/am-org-role-mapping-service/values.yaml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1929

#1930 DTSAM-320 Remove the custom V15 key vault secrets.
  infrastructure/main.tf
Labels: ns:am, prd:am, aat/destroy, prod/destroy, rel:am-org-role-mapping-service-pr-1930

#1923 DTSAM-317 Update processing of REFRESH_JOB env var
  src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshJobConfigServiceIntegrationTest.java
  src/integrationTest/resources/sql/insert_refresh_jobs.sql
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/config/JobConfiguration.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshJobConfigService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/config/JobConfigurationTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/RefreshJobConfigServiceTest.java
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-1923
