Repository hmcts/am-org-role-mapping-service, pull requests merged in 2025-03, with the labels that each got.

#2260 DTSAM-795 Tomcat Version Revert for ORM and JBS to 9.0.98 from 9.0.10…
  build.gradle
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-2260

#2263 DTSAM-149 Enable 'iac_jrd_1_1' ORM flag in PROD
  src/main/resources/db/migration/V20250305_149__DTSAM-149_Enable_iac_jrd_1_1_Prod.sql
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-2263

#2262 COT-945 Added additional worktype for various roles for Civil
  src/functionalTest/resources/features/F-007 - Create CIVIL Staff and Judicial Role Assignments/F-007.feature
  src/functionalTest/resources/features/F-007 - Create CIVIL Staff and Judicial Role Assignments/S-007.03_AAA6.td.json
  src/functionalTest/resources/features/F-007 - Create CIVIL Staff and Judicial Role Assignments/S-007.03_AAA7.td.json
  src/functionalTest/resources/features/F-007 - Create CIVIL Staff and Judicial Role Assignments/S-007.04_AAA6.td.json
  src/functionalTest/resources/features/F-007 - Create CIVIL Staff and Judicial Role Assignments/S-007.04_AAA7.td.json
  src/functionalTest/resources/features/F-007 - Create CIVIL Staff and Judicial Role Assignments/S-007.09_AAA6.td.json
  src/functionalTest/resources/features/F-007 - Create CIVIL Staff and Judicial Role Assignments/S-007.09_AAA7.td.json
  src/functionalTest/resources/features/F-007 - Create CIVIL Staff and Judicial Role Assignments/S-007.10_AAA6.td.json
  src/functionalTest/resources/features/F-007 - Create CIVIL Staff and Judicial Role Assignments/S-007.10_AAA7.td.json
  src/functionalTest/resources/features/F-007 - Create CIVIL Staff and Judicial Role Assignments/S-062.td.json
  src/functionalTest/resources/features/F-007 - Create CIVIL Staff and Judicial Role Assignments/S-064.td.json
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/model/enums/FeatureFlagEnum.java
  src/main/resources/db/migration/V20250226_945__COT-945_CIVIL_WA_2_2_base_flag_addition.sql
  src/main/resources/validationrules/civil/civil-admin-mapping.drl
  src/main/resources/validationrules/civil/civil-ctsc-mapping.drl
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/DroolCivilStaffOrgRolesTest.java
Labels: ns:am, prd:am, enable_keep_helm, rel:am-org-role-mapping-service-pr-2262

#2269 Dtsam 799 sonarqube issues
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/OrganisationService.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/PrdService.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/data/AccessTypeTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/data/BatchLastRunTimestampTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/PrdServiceTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/helper/AccessTypesBuilderTest.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/monitoring/service/ProcessEventTrackerTest.java
Labels: ns:am, prd:am, aat/add-or-update, prod/add-or-update, rel:am-org-role-mapping-service-pr-2269

#2270 DTSAM-627 Enable 'iac_wa_1_3' AM ORM flag in PROD
  src/main/resources/db/migration/V20250312_627__DTSAM-627_Enable_iac_wa_1_3_Prod.sql
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-2270

#2272 DTSAM-672 Enable 'privatelaw_wa_1_5' AM ORM flag in PROD
  src/main/resources/db/migration/V20250305_672__DTSAM-672_Enable_privatelaw_wa_1_5_Prod.sql
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-2272

#2278 DTSAM-781 Enable 'publiclaw_wa_1_7' ORM flag in PROD
  src/main/resources/db/migration/V20250317_781__DTSAM-781_Enable_publiclaw_wa_1_7_Prod.sql
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-2278

#1899 DTSAM-283 update p3 upsert query + refactor OrganisationService
  src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/data/OrganisationRefreshQueueRepositoryIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/data/OrganisationRefreshQueueRepository.java
  src/main/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/OrganisationService.java
  src/test/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/OrganisationServiceTest.java
Labels: ns:am, prd:am, aat/add-or-update, prod/add-or-update, rel:am-org-role-mapping-service-pr-1899

#1904 DTSAM-284 add default timestamp
  src/integrationTest/java/uk/gov/hmcts/reform/orgrolemapping/domain/service/OrganisationServiceIntegrationTest.java
  src/integrationTest/resources/sql/insert_batch_last_run.sql
  src/main/resources/db/migration/V20240108_99__GA-99-Create-table-batch_last_run_timestamp.sql
Labels: ns:am, prd:am, aat/add-or-update, prod/add-or-update, rel:am-org-role-mapping-service-pr-1904

#2284 DTSAM-812 Upgrade Fortify Client to 1.4.8 AM(ORM/RAS/JBS) repos
  Jenkinsfile_CNP
  build.gradle
Labels: ns:am, prd:am, enable_keep_helm, rel:am-org-role-mapping-service-pr-2284

#2273 CME-393: OCI image
  charts/am-org-role-mapping-service/Chart.yaml
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-2273

#2285 DTSAM-815 Re-enable ASB FTAs
  Jenkinsfile_CNP
Labels: ns:am, prd:am, rel:am-org-role-mapping-service-pr-2285
